language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - "pip install -r requirements-test.txt"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
# command to run tests
script: py.test